syntax = "proto3";

service ChunkReferenceService
{
    rpc GetChunkByReference (GetChunkByReference_Req) returns (GetChunkByReference_Res);
    rpc GetChunkByKey (GetChunkByKey_Req) returns (GetChunkByKey_Res);
}

message GetChunkByReference_Req
{
    uint64 bucket_id = 1;
    uint64 bucket_index = 2;
}

message GetChunkByReference_Res
{
    bool found = 1;
    bytes chunk = 2;
}

message GetChunkByKey_Req
{
    string chunk_key = 1;
}

message GetChunkByKey_Res
{
    bool found = 1;
    bytes chunk = 2;
}
